In [ ]:
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests as rq

In [ ]:
url = "https://cescrajasthan.co.in/besl/pages/event/announcement/power_outage.php"

try:
    page = rq.get(url)
    page.raise_for_status()
except page.exceptions.HTTPError as e:
    if e.response.status_code == 404:
            print("API returned a 404 error: Not Found")
    else:
            print("API returned an error:", e)
except Exception as e:
        print("An error occurred:", e)

In [3]:
soup = bs(page.text, 'html')
soup

<title>Power Outage Information | CESC Rajasthan</title>
<!DOCTYPE html>

<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.

    Created on      : June 30, 2017
    Author          : Chiranjit Ghosh
    Last Modified on: October 13, 2017
-->
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>BESL - Bharatpur Electricity Services Limited</title>
<link href="https://cescrajasthan.co.in:/besl/assets/images/favicon.ico" rel="SHORTCUT ICON"/>
<!-- Bootstrap -->
<link href="https://cescrajasthan.co.in:/assets/bootstrap/bootstrap.min.css" rel="stylesheet"/>
<link href="https://cescrajasthan.co.in:/assets/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://cescrajasthan.co.in:/assets/bootstrap/jquery.min.1.11.3.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://cescrajasthan.co.in:/assets/bootstrap/bootstrap.min.js"></script>
<!-- Custom css -->
<link href="https://cescrajasthan.co.in:/besl/assets/css/custom.css" rel="stylesheet"/>
<script src="https://cescrajasthan.co.in:/assets/js/date-time-picker.min.js" type="text/javascript"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-111926155-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-111926155-1');
</script>
</head>
<body>
<div class="container-fluid pre_header">
<div class="container">
<div class="row">
<!-- START: TOP BAR LEFT PART -->
<div class="col-md-8 col-sm-8">
<i class="fa fa-phone"></i>
<span>
                            Helpline: <b>0141-3532000</b>

                            18002001912

                            18003301912

                            1912
                        </span>
</div>
<!-- END: TOP BAR LEFT PART -->
<!-- START: TOP BAR LAST PART -->
<div class="col-md-3 col-sm-3">
<!--<a href="myaccount.php">
                            <i class="fa fa-user"></i><span>My Account</span>
                        </a>-->
<ul class="social-footer list-unstyled list-inline pull-right top_social">
<!--<li><a href="javascript:void(0);" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>-->
<!--<li><a href="javascript:void(0);" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>-->
<li><i class="fa fa-whatsapp"></i> 7230044001</li>
</ul>
</div>
<!-- END: TOP BAR LAST PART -->
</div>
</div>
</div>
<div class="container-fluid header">
<div id="nav-wrapper"><!--nav-wrapper-->
<div class="" id="navigation"><!--header-->
<div class="col-sm-12"><!--col-md-12-->
<div id="nav"><!--nav-->
<div class="row site_title_div">
<div class="col-sm-2 col-xs-2 border_right">
<a href="https://cescrajasthan.co.in:/">
<img alt="RPSG" class="img-responsive" src="https://cescrajasthan.co.in:/besl/assets/images/RPSG-LOGO-FINAL.png"/>
</a>
</div>
<div class="col-sm-8 col-xs-8 site_name">
<img alt="besl" class="img-responsive" src="https://cescrajasthan.co.in:/besl/assets/images/beslban.jpg"/>
</div>
<div class="col-sm-2 col-xs-2 border_left">
<a class="pull-right padding_right0" href="https://cescrajasthan.co.in:/">
<img alt="CESC Rajasthan" class="img-responsive" src="https://cescrajasthan.co.in:/besl/assets/images/cesc-raj.png"/>
</a>
</div>
</div>
<nav class="navbar navbar-default my_nav" role="navigation">
<div class="container-fluid">
<div class="navbar-header pull-right border_left clearfix">
<button class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">
<li id="home"><a href="https://cescrajasthan.co.in:/besl/pages/event/">Home</a></li>
<li><a href="#" onclick="$('#detail').load('/kotawebsite/new_user_register.jsp?df=BESL');">Register With Us</a></li>
<li><a href="https://services.cesc.co.in/jascnaesr/besl/qbpaybesl.php" target="new">Quick Bill Pay</a></li>
<li><a href="https://bit.ly/2mQVHJ9" target="new">Bharat BillPay</a></li>
<li><a href="https://cescrajasthan.co.in/newconnection/nc_online_add_request.jsp?mkr=ONLINE&amp;df=BESL" target="new">New Connection</a></li>
<li><a href="https://cescrajasthan.co.in:/besl/pages/event/uploads/JVVNL Tariff-2025.10.22.pdf" target="new">Tariff</a></li>
</ul>
</div>
<!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
</div><!-- /.nav -->
</div><!--col-md-12-->
<div class="clearfix"></div>
</div><!--header-->
</div>
</div>
<div class="container-fluid">
<div class="container inner_content" id="detail">
<div class="col-sm-12">
<h2>Power Outage Information</h2>
</div>
<div class="col-md-12 body_content_middle" style="border:1px solid #dddddd;">
<div class="row bg-primary">
<div class="col-sm-7">Affected Area (at 28/02/2026 10:15)</div>
<div class="col-sm-3">Duration (From - To)</div>
</div>
<div class="row" style="border-bottom:1px solid #dddddd; background-color:#d1ebff">
<div class="col-sm-7">#1 - HEERADAS, SUBHAS NAGAR, ANAH GATE PARK, BALAJI CHOWK SUBHASH NAGAR, BALVEER SINGH CHOUDHARY HOUSE, C-51 HOSUE PUSHPA SUBHASH NAGAR, COLD STORAGE, DR. AKANA SINGH NEAR MOBILE TOWER, GORAKHDHAM COLONY, GOYAL STONE, HEERA DAS PUMP HOUSE, IN FRONT OF BHIMA RESORT, IN FRONT OF RAM BABU E-MITRA CHOTTALE CIRCLE, INDIAN SENIOR SCHOOL KE PASS, JAGAN NATH PURI 1, JAGAN NATH PURI 2, LALITA DEVI, MADHO SINGH SUBHASH NAGAR, MOBILE TOWER ANAHE GATE, NEAR ATALBAND WATER WORKS, NEAR BHIMA RESORT, NEAR JAGANNATHPURI, NEAR JAGANNATHPURI FLATS, NEAR MOBILE TOWER, NEAR N.M TAILOR, NEAR OF RAGHU AATA CHAKKI, NEAR OM PRAKASH FAUJI CHAKKI SUBHASH NAGAR, NEAR S ENTERPRISE, NEAR SHAMSHAN GHAT, NEAR SHAMSHAN GHAT, NEAR SINSINWAR PROVISION STORE, OM PRAKESH FOJI CHAKKI WALE SUBASH NAGAR, RIGVED HOSPITAL INDRA NAGAR HEERADAS, S. ENTERPRISES, SATYAM AGGRICULTURE WORKS, SHIVAM TENT HOUSE, SHYAM ATTA CHAKKI, SITARAM BARDHAN GODOWN, TEMPLE ASHOK VIHAR COLONY, W/W HARIJAN BASTI ANAHE GATE</div>
<div class="col-sm-3" style="color: #ff0000;">28/02/2026 09:43
   -   28/02/2026 10:59</div>
</div>
<div class="row" style="border-bottom:1px solid #dddddd; background-color:#ffffff">
<div class="col-sm-7">#2 - SPM NAGAR, ANAND NAGAR, AMARVIDHYA MANDIR SCHOOL, AMBEDKAR CHATRABAS, ANOKHI HOTEL, ANOKHI HOTEL JAIPUR BYPASS, AUTO AGRIC, BACK SIDE KAMALPURA, BACK SIDE MANDI ANAND NAGAR, BAJRANG COLONY, BAJRANG COLONY 1, BHAGWAN TALWKIES, BHAGWAN TAWLKIES-1, BHARTI FALI FARM, FARUKH ENGINEERING, GARG FURNITURE MARWARA ROAD ANAND NAGAR, GOGAJI TEMPLE SECTOR 13, GOPAL JI SUPER SPECIALITY HOSPITAL, GRAND CP, HOUSING POLICY, JAGHINA COLONY, JAGMOHANPURA, JANTA COLONY, KAUWA KA NAGLA, KRISHI UPAJ MANDI, KRISHI UPAJ MANDI SAMITI, KRISHNA BUILDING, KRISHNA HOTEL, KUMHER GATE SAMSHAN, MAHA LAXMI KRISHI YANTRALAYA, MAHADEV CONSTRUCTION, MASTI HOUSE, MOBILE TOWER IDHGAHA COLONY, MURWARA ROAD, NEAR GIRRAJ MEDICAL, NEAR IDEA TOWER, NEAR K MART SPM NAGAR, NEAR MICRO PC SOLUTION MARWARA ROAD ANAND NAGAR, NEAR SPM NAGAR GSS, NEETA GOYEL, NIRALA VIHAR COLONY, PINTU USHRANI JANTA COLONY, PNB BANK AD, RADHEY PIPE UDYOG, RAHAMANPURA, RAHAMANPURA - 1, RAHAMANPURA - 2, RAHAMANPURA-4, RAHMANPURA - 3, RAJ KIYA SCHOOL ANAND NAGAR, RAJASTHAN ASSOCIATION, RAMESHWER MUSHALE ANAND NAGAR, RAMESHWER MUSHALE ANAND NAGAR 1, RONAK MARRIAGE HALL, RONAK MARRIAGE HALL 1, S.R ATTA CHAKTI, SAI MANDIR ANAND NAGAR, SAI MANDIR ANAND NAGAR-1, SHAHNAI RESORT, SHYAM NAGAR RAHMANPURA, SWARAJ ARYA AGENCY, TAJ AGRO INDS.ANAND NAGAR, TATA MOTERS, VIDHYA FILLING STATION, WARD NO.1 KAMAL PURA VILLAGE</div>
<div class="col-sm-3" style="color: #ff0000;">28/02/2026 12:00
   -   28/02/2026 13:00</div>
</div>
</div>
</div>
</div>
<div class="container">
<div class="row quick_links">
<!--<div class="col-sm-2 col-xs-6 quick_item">
            <a href="#" onclick="$('#detail').load('/kotawebsite/kno_input.jsp?df=BESL&option=VIEWBILL');">
                <p>View / Print Bill</p>
            </a>
        </div>-->
<div class="col-sm-2 col-xs-6 quick_item">
<a href="https://cescrajasthan.co.in:/besl/pages/event/announcement/power_outage.php">
<p>Planned Outage</p>
</a>
</div>
<div class="col-sm-2 col-xs-6 quick_item">
<a href="https://cescrajasthan.co.in:/besl/pages/event/uploads/power_consump_guide.pdf" target="new">
<p>Power Consumption Guide</p>
</a>
</div>
<div class="col-sm-2 col-xs-6 quick_item" id="supply">
<a href="https://cescrajasthan.co.in:/supply/" target="_blank">
<p>Report Supply Off</p>
</a>
</div>
<div class="col-sm-2 col-xs-6 quick_item" id="power_theft">
<a href="https://cescrajasthan.co.in:/besl/pages/event/power_theft/power_theft.php">
<p>Report Power Theft</p>
</a>
</div>
<div class="col-sm-2 col-xs-6 quick_item" id="power_theft">
<a href="https://cescrajasthan.co.in:/besl/pages/event/uploads/BESL IGR CELL 2025_FINAL.pdf" target="new">
<p>Grievance Redressal System</p>
</a>
</div>
<!-- <div class="col-sm-2 col-xs-6 quick_item" id="chat_with_us">
           <a href="https://cescrajasthan.co.in:/besl/pages/event/chat_with_us.php">
                <p>Online Chat</p>
            </a>
        </div> -->
</div>
</div>
<footer>
<div class="container-fluid">
<div class="row footer_big">
<div class="col-xs-12 col-sm-2 col-md-2">
<h2>Corporate Information</h2>
<ul class="group_links">
<li id="about_us"><a href="https://cescrajasthan.co.in:/besl/pages/event/corporate_information/about_us.php">About Us</a></li>
<li id="vision"><a href="https://cescrajasthan.co.in:/besl/pages/event/uploads/Core_Values.pdf" target="new">Core Values</a></li>
<li id="rp_sg"><a href="https://cescrajasthan.co.in:/besl/pages/event/corporate_information/rp-sg.php">RP-SG Group</a></li>
<li id="leadership_team"><a href="https://cescrajasthan.co.in:/besl/pages/event/corporate_information/leadership_team.php">Leadership Team</a></li>
<!--<li id="media"><a href="https://cescrajasthan.co.in:/besl/pages/event/corporate_information/media.php">Media</a></li>-->
<!-- <li><a href="http://raj.nic.in/cal/cal.htm" target="new">Holiday List</a></li> -->
</ul>
</div>
<div class="col-xs-12 col-sm-2 col-md-2">
<h2>Announcement</h2>
<ul class="group_links">
<li id="power_outage"><a href="https://cescrajasthan.co.in:/besl/pages/event/announcement/power_outage.php">Power Outage Information</a></li>
<li id="cash_office_timings"><a href="https://cescrajasthan.co.in:/besl/pages/event/announcement/cash_office_timings.php">Cash Office Timings</a></li>
<!--<li id="news"><a href="https://cescrajasthan.co.in:/besl/pages/event/announcement/news.php">News</a></li>-->
</ul>
</div>
<div class="col-xs-12 col-sm-2 col-md-2">
<h2>Information</h2>
<ul class="group_links">
<!--<li id="submit_resume"><a href="https://cescrajasthan.co.in:/besl/pages/event/careers/submit_resume.php">Submit your Resume Online</a></li>-->
<li><a href="https://cescrajasthan.co.in:/besl/pages/event/uploads/booklet/Be guided Stay Safe redesigned_BESL.pdf" target="new">Be guided Stay Safe</a></li>
<li><a href="https://cescrajasthan.co.in:/besl/pages/event/uploads/booklet/Know your equipment, know your running cost redesigned_BESL.pdf" target="new">Know your equipment, know your running cost</a></li>
<li><a href="https://cescrajasthan.co.in:/besl/pages/event/uploads/booklet/Save energy. Save the environment redesigned_BESL.pdf" target="new">Save energy. Save the environment</a></li>
</ul>
</div>
<div class="col-xs-12 col-sm-2 col-md-2">
<h2>Contact Us</h2>
<ul class="group_links">
<li id="contact_us"><a href="https://cescrajasthan.co.in:/besl/pages/event/contact_us/map.php">Corporate Office</a></li>
</ul>
</div>
<div class="col-xs-12 col-sm-2 col-md-2">
<div class="row">
<div class="col-sm-12">
<a href="javasctipt:void(0);">
<img alt="Office Locator" class="img-responsive" src="https://cescrajasthan.co.in:/besl/assets/images/locator.png"/>
</a>
</div>
<div class="col-sm-12 text-right terms">
<!--<a href="javascript:void(0);">Terms of Use</a>-->
</div>
</div>
</div>
</div>
<div class="container">
<div class="row footer_big">
<div class="col-sm-9 footer_left">
<p class="footer_txt">Bharatpur Electricity Services Limited - A franchisee of JVVNL &amp; a wholly-owned subsidiary of CESC Limited - All Rights Reserved.</p>
</div>
<div class="col-sm-3 footer_right">
<p class="footer_txt">CIN : U40100WB2012PLC181314</p>
</div>
</div>
</div>
</div>
</footer>
</body>
</html>
<script type="text/javascript">
function GoToListMapPage(url,flag)
{
    document.nav_form.office_type.value=flag;
    document.nav_form.action=url;
    document.nav_form.submit();
    return true;
}
</script>
<!-- START: for active menu -->
<script type="text/javascript">
    $(function () {
        $('#power_outage').addClass('active_menu');
    });
</script>
<!-- END: for active menu -->

In [ ]:
try:
    table = soup.find_all('div', class_ = 'body_content_middle')[0]
except:
    print("Currently no data is available!")

<div class="col-md-12 body_content_middle" style="border:1px solid #dddddd;">
<div class="row bg-primary">
<div class="col-sm-7">Affected Area (at 28/02/2026 10:15)</div>
<div class="col-sm-3">Duration (From - To)</div>
</div>
<div class="row" style="border-bottom:1px solid #dddddd; background-color:#d1ebff">
<div class="col-sm-7">#1 - HEERADAS, SUBHAS NAGAR, ANAH GATE PARK, BALAJI CHOWK SUBHASH NAGAR, BALVEER SINGH CHOUDHARY HOUSE, C-51 HOSUE PUSHPA SUBHASH NAGAR, COLD STORAGE, DR. AKANA SINGH NEAR MOBILE TOWER, GORAKHDHAM COLONY, GOYAL STONE, HEERA DAS PUMP HOUSE, IN FRONT OF BHIMA RESORT, IN FRONT OF RAM BABU E-MITRA CHOTTALE CIRCLE, INDIAN SENIOR SCHOOL KE PASS, JAGAN NATH PURI 1, JAGAN NATH PURI 2, LALITA DEVI, MADHO SINGH SUBHASH NAGAR, MOBILE TOWER ANAHE GATE, NEAR ATALBAND WATER WORKS, NEAR BHIMA RESORT, NEAR JAGANNATHPURI, NEAR JAGANNATHPURI FLATS, NEAR MOBILE TOWER, NEAR N.M TAILOR, NEAR OF RAGHU AATA CHAKKI, NEAR OM PRAKASH FAUJI CHAKKI SUBHASH NAGAR, NEAR S ENTERPRISE, NEAR SHAMSHAN GHAT, NEAR SHAMSHAN GHAT, NEAR SINSINWAR PROVISION STORE, OM PRAKESH FOJI CHAKKI WALE SUBASH NAGAR, RIGVED HOSPITAL INDRA NAGAR HEERADAS, S. ENTERPRISES, SATYAM AGGRICULTURE WORKS, SHIVAM TENT HOUSE, SHYAM ATTA CHAKKI, SITARAM BARDHAN GODOWN, TEMPLE ASHOK VIHAR COLONY, W/W HARIJAN BASTI ANAHE GATE</div>
<div class="col-sm-3" style="color: #ff0000;">28/02/2026 09:43
   -   28/02/2026 10:59</div>
</div>
<div class="row" style="border-bottom:1px solid #dddddd; background-color:#ffffff">
<div class="col-sm-7">#2 - SPM NAGAR, ANAND NAGAR, AMARVIDHYA MANDIR SCHOOL, AMBEDKAR CHATRABAS, ANOKHI HOTEL, ANOKHI HOTEL JAIPUR BYPASS, AUTO AGRIC, BACK SIDE KAMALPURA, BACK SIDE MANDI ANAND NAGAR, BAJRANG COLONY, BAJRANG COLONY 1, BHAGWAN TALWKIES, BHAGWAN TAWLKIES-1, BHARTI FALI FARM, FARUKH ENGINEERING, GARG FURNITURE MARWARA ROAD ANAND NAGAR, GOGAJI TEMPLE SECTOR 13, GOPAL JI SUPER SPECIALITY HOSPITAL, GRAND CP, HOUSING POLICY, JAGHINA COLONY, JAGMOHANPURA, JANTA COLONY, KAUWA KA NAGLA, KRISHI UPAJ MANDI, KRISHI UPAJ MANDI SAMITI, KRISHNA BUILDING, KRISHNA HOTEL, KUMHER GATE SAMSHAN, MAHA LAXMI KRISHI YANTRALAYA, MAHADEV CONSTRUCTION, MASTI HOUSE, MOBILE TOWER IDHGAHA COLONY, MURWARA ROAD, NEAR GIRRAJ MEDICAL, NEAR IDEA TOWER, NEAR K MART SPM NAGAR, NEAR MICRO PC SOLUTION MARWARA ROAD ANAND NAGAR, NEAR SPM NAGAR GSS, NEETA GOYEL, NIRALA VIHAR COLONY, PINTU USHRANI JANTA COLONY, PNB BANK AD, RADHEY PIPE UDYOG, RAHAMANPURA, RAHAMANPURA - 1, RAHAMANPURA - 2, RAHAMANPURA-4, RAHMANPURA - 3, RAJ KIYA SCHOOL ANAND NAGAR, RAJASTHAN ASSOCIATION, RAMESHWER MUSHALE ANAND NAGAR, RAMESHWER MUSHALE ANAND NAGAR 1, RONAK MARRIAGE HALL, RONAK MARRIAGE HALL 1, S.R ATTA CHAKTI, SAI MANDIR ANAND NAGAR, SAI MANDIR ANAND NAGAR-1, SHAHNAI RESORT, SHYAM NAGAR RAHMANPURA, SWARAJ ARYA AGENCY, TAJ AGRO INDS.ANAND NAGAR, TATA MOTERS, VIDHYA FILLING STATION, WARD NO.1 KAMAL PURA VILLAGE</div>
<div class="col-sm-3" style="color: #ff0000;">28/02/2026 12:00
   -   28/02/2026 13:00</div>
</div>
</div>

In [5]:
power_titles = table.find_all('div', class_ = 'bg-primary')
power_titles

[<div class="row bg-primary">
 <div class="col-sm-7">Affected Area (at 28/02/2026 10:15)</div>
 <div class="col-sm-3">Duration (From - To)</div>
 </div>]

In [6]:
power_table_titles = [titles.text.strip().split("\n") for titles in power_titles][0]
power_table_titles

['Affected Area (at 28/02/2026 10:15)', 'Duration (From - To)']

In [7]:
df = pd.DataFrame(columns=power_table_titles)
df

Empty DataFrame
Columns: [Affected Area (at 28/02/2026 10:15), Duration (From - To)]
Index: []

In [8]:
columns_data = table.find_all('div', class_= 'row')[1:]
columns_data

[<div class="row" style="border-bottom:1px solid #dddddd; background-color:#d1ebff">
 <div class="col-sm-7">#1 - HEERADAS, SUBHAS NAGAR, ANAH GATE PARK, BALAJI CHOWK SUBHASH NAGAR, BALVEER SINGH CHOUDHARY HOUSE, C-51 HOSUE PUSHPA SUBHASH NAGAR, COLD STORAGE, DR. AKANA SINGH NEAR MOBILE TOWER, GORAKHDHAM COLONY, GOYAL STONE, HEERA DAS PUMP HOUSE, IN FRONT OF BHIMA RESORT, IN FRONT OF RAM BABU E-MITRA CHOTTALE CIRCLE, INDIAN SENIOR SCHOOL KE PASS, JAGAN NATH PURI 1, JAGAN NATH PURI 2, LALITA DEVI, MADHO SINGH SUBHASH NAGAR, MOBILE TOWER ANAHE GATE, NEAR ATALBAND WATER WORKS, NEAR BHIMA RESORT, NEAR JAGANNATHPURI, NEAR JAGANNATHPURI FLATS, NEAR MOBILE TOWER, NEAR N.M TAILOR, NEAR OF RAGHU AATA CHAKKI, NEAR OM PRAKASH FAUJI CHAKKI SUBHASH NAGAR, NEAR S ENTERPRISE, NEAR SHAMSHAN GHAT, NEAR SHAMSHAN GHAT, NEAR SINSINWAR PROVISION STORE, OM PRAKESH FOJI CHAKKI WALE SUBASH NAGAR, RIGVED HOSPITAL INDRA NAGAR HEERADAS, S. ENTERPRISES, SATYAM AGGRICULTURE WORKS, SHIVAM TENT HOUSE, SHYAM ATTA CHAKKI, SITARAM BARDHAN GODOWN, TEMPLE ASHOK VIHAR COLONY, W/W HARIJAN BASTI ANAHE GATE</div>
 <div class="col-sm-3" style="color: #ff0000;">28/02/2026 09:43
    -   28/02/2026 10:59</div>
 </div>,
 <div class="row" style="border-bottom:1px solid #dddddd; background-color:#ffffff">
 <div class="col-sm-7">#2 - SPM NAGAR, ANAND NAGAR, AMARVIDHYA MANDIR SCHOOL, AMBEDKAR CHATRABAS, ANOKHI HOTEL, ANOKHI HOTEL JAIPUR BYPASS, AUTO AGRIC, BACK SIDE KAMALPURA, BACK SIDE MANDI ANAND NAGAR, BAJRANG COLONY, BAJRANG COLONY 1, BHAGWAN TALWKIES, BHAGWAN TAWLKIES-1, BHARTI FALI FARM, FARUKH ENGINEERING, GARG FURNITURE MARWARA ROAD ANAND NAGAR, GOGAJI TEMPLE SECTOR 13, GOPAL JI SUPER SPECIALITY HOSPITAL, GRAND CP, HOUSING POLICY, JAGHINA COLONY, JAGMOHANPURA, JANTA COLONY, KAUWA KA NAGLA, KRISHI UPAJ MANDI, KRISHI UPAJ MANDI SAMITI, KRISHNA BUILDING, KRISHNA HOTEL, KUMHER GATE SAMSHAN, MAHA LAXMI KRISHI YANTRALAYA, MAHADEV CONSTRUCTION, MASTI HOUSE, MOBILE TOWER IDHGAHA COLONY, MURWARA ROAD, NEAR GIRRAJ MEDICAL, NEAR IDEA TOWER, NEAR K MART SPM NAGAR, NEAR MICRO PC SOLUTION MARWARA ROAD ANAND NAGAR, NEAR SPM NAGAR GSS, NEETA GOYEL, NIRALA VIHAR COLONY, PINTU USHRANI JANTA COLONY, PNB BANK AD, RADHEY PIPE UDYOG, RAHAMANPURA, RAHAMANPURA - 1, RAHAMANPURA - 2, RAHAMANPURA-4, RAHMANPURA - 3, RAJ KIYA SCHOOL ANAND NAGAR, RAJASTHAN ASSOCIATION, RAMESHWER MUSHALE ANAND NAGAR, RAMESHWER MUSHALE ANAND NAGAR 1, RONAK MARRIAGE HALL, RONAK MARRIAGE HALL 1, S.R ATTA CHAKTI, SAI MANDIR ANAND NAGAR, SAI MANDIR ANAND NAGAR-1, SHAHNAI RESORT, SHYAM NAGAR RAHMANPURA, SWARAJ ARYA AGENCY, TAJ AGRO INDS.ANAND NAGAR, TATA MOTERS, VIDHYA FILLING STATION, WARD NO.1 KAMAL PURA VILLAGE</div>
 <div class="col-sm-3" style="color: #ff0000;">28/02/2026 12:00
    -   28/02/2026 13:00</div>
 </div>]

In [9]:
for rows in columns_data:
    row_data = rows.find_all('div', class_= ['col-sm-7', 'col-sm-3'])
    # individual_row_data = [data.text.strip() for data in row_data]
    # print(individual_row_data)
    individual_row_data = []
    for data in row_data:
        text = data.text.strip()         # remove leading/trailing spaces
        text = text.replace('\r', '')    # remove carriage returns
        text = text.replace('\n', '')    # remove newlines
        text = text.replace('\xa0', ' ') # replace non-breaking space with normal space
        text = ' '.join(text.split())    # collapse multiple spaces into one
        individual_row_data.append(text)
        print(individual_row_data)
    length = len(df)
    df.loc[length] = individual_row_data

['#1 - HEERADAS, SUBHAS NAGAR, ANAH GATE PARK, BALAJI CHOWK SUBHASH NAGAR, BALVEER SINGH CHOUDHARY HOUSE, C-51 HOSUE PUSHPA SUBHASH NAGAR, COLD STORAGE, DR. AKANA SINGH NEAR MOBILE TOWER, GORAKHDHAM COLONY, GOYAL STONE, HEERA DAS PUMP HOUSE, IN FRONT OF BHIMA RESORT, IN FRONT OF RAM BABU E-MITRA CHOTTALE CIRCLE, INDIAN SENIOR SCHOOL KE PASS, JAGAN NATH PURI 1, JAGAN NATH PURI 2, LALITA DEVI, MADHO SINGH SUBHASH NAGAR, MOBILE TOWER ANAHE GATE, NEAR ATALBAND WATER WORKS, NEAR BHIMA RESORT, NEAR JAGANNATHPURI, NEAR JAGANNATHPURI FLATS, NEAR MOBILE TOWER, NEAR N.M TAILOR, NEAR OF RAGHU AATA CHAKKI, NEAR OM PRAKASH FAUJI CHAKKI SUBHASH NAGAR, NEAR S ENTERPRISE, NEAR SHAMSHAN GHAT, NEAR SHAMSHAN GHAT, NEAR SINSINWAR PROVISION STORE, OM PRAKESH FOJI CHAKKI WALE SUBASH NAGAR, RIGVED HOSPITAL INDRA NAGAR HEERADAS, S. ENTERPRISES, SATYAM AGGRICULTURE WORKS, SHIVAM TENT HOUSE, SHYAM ATTA CHAKKI, SITARAM BARDHAN GODOWN, TEMPLE ASHOK VIHAR COLONY, W/W HARIJAN BASTI ANAHE GATE']
['#1 - HEERADAS, SUBHAS NAGAR, ANAH GATE PARK, BALAJI CHOWK SUBHASH NAGAR, BALVEER SINGH CHOUDHARY HOUSE, C-51 HOSUE PUSHPA SUBHASH NAGAR, COLD STORAGE, DR. AKANA SINGH NEAR MOBILE TOWER, GORAKHDHAM COLONY, GOYAL STONE, HEERA DAS PUMP HOUSE, IN FRONT OF BHIMA RESORT, IN FRONT OF RAM BABU E-MITRA CHOTTALE CIRCLE, INDIAN SENIOR SCHOOL KE PASS, JAGAN NATH PURI 1, JAGAN NATH PURI 2, LALITA DEVI, MADHO SINGH SUBHASH NAGAR, MOBILE TOWER ANAHE GATE, NEAR ATALBAND WATER WORKS, NEAR BHIMA RESORT, NEAR JAGANNATHPURI, NEAR JAGANNATHPURI FLATS, NEAR MOBILE TOWER, NEAR N.M TAILOR, NEAR OF RAGHU AATA CHAKKI, NEAR OM PRAKASH FAUJI CHAKKI SUBHASH NAGAR, NEAR S ENTERPRISE, NEAR SHAMSHAN GHAT, NEAR SHAMSHAN GHAT, NEAR SINSINWAR PROVISION STORE, OM PRAKESH FOJI CHAKKI WALE SUBASH NAGAR, RIGVED HOSPITAL INDRA NAGAR HEERADAS, S. ENTERPRISES, SATYAM AGGRICULTURE WORKS, SHIVAM TENT HOUSE, SHYAM ATTA CHAKKI, SITARAM BARDHAN GODOWN, TEMPLE ASHOK VIHAR COLONY, W/W HARIJAN BASTI ANAHE GATE', '28/02/2026 09:43 - 28/02/2026 10:59']
['#2 - SPM NAGAR, ANAND NAGAR, AMARVIDHYA MANDIR SCHOOL, AMBEDKAR CHATRABAS, ANOKHI HOTEL, ANOKHI HOTEL JAIPUR BYPASS, AUTO AGRIC, BACK SIDE KAMALPURA, BACK SIDE MANDI ANAND NAGAR, BAJRANG COLONY, BAJRANG COLONY 1, BHAGWAN TALWKIES, BHAGWAN TAWLKIES-1, BHARTI FALI FARM, FARUKH ENGINEERING, GARG FURNITURE MARWARA ROAD ANAND NAGAR, GOGAJI TEMPLE SECTOR 13, GOPAL JI SUPER SPECIALITY HOSPITAL, GRAND CP, HOUSING POLICY, JAGHINA COLONY, JAGMOHANPURA, JANTA COLONY, KAUWA KA NAGLA, KRISHI UPAJ MANDI, KRISHI UPAJ MANDI SAMITI, KRISHNA BUILDING, KRISHNA HOTEL, KUMHER GATE SAMSHAN, MAHA LAXMI KRISHI YANTRALAYA, MAHADEV CONSTRUCTION, MASTI HOUSE, MOBILE TOWER IDHGAHA COLONY, MURWARA ROAD, NEAR GIRRAJ MEDICAL, NEAR IDEA TOWER, NEAR K MART SPM NAGAR, NEAR MICRO PC SOLUTION MARWARA ROAD ANAND NAGAR, NEAR SPM NAGAR GSS, NEETA GOYEL, NIRALA VIHAR COLONY, PINTU USHRANI JANTA COLONY, PNB BANK AD, RADHEY PIPE UDYOG, RAHAMANPURA, RAHAMANPURA - 1, RAHAMANPURA - 2, RAHAMANPURA-4, RAHMANPURA - 3, RAJ KIYA SCHOOL ANAND NAGAR, RAJASTHAN ASSOCIATION, RAMESHWER MUSHALE ANAND NAGAR, RAMESHWER MUSHALE ANAND NAGAR 1, RONAK MARRIAGE HALL, RONAK MARRIAGE HALL 1, S.R ATTA CHAKTI, SAI MANDIR ANAND NAGAR, SAI MANDIR ANAND NAGAR-1, SHAHNAI RESORT, SHYAM NAGAR RAHMANPURA, SWARAJ ARYA AGENCY, TAJ AGRO INDS.ANAND NAGAR, TATA MOTERS, VIDHYA FILLING STATION, WARD NO.1 KAMAL PURA VILLAGE']
['#2 - SPM NAGAR, ANAND NAGAR, AMARVIDHYA MANDIR SCHOOL, AMBEDKAR CHATRABAS, ANOKHI HOTEL, ANOKHI HOTEL JAIPUR BYPASS, AUTO AGRIC, BACK SIDE KAMALPURA, BACK SIDE MANDI ANAND NAGAR, BAJRANG COLONY, BAJRANG COLONY 1, BHAGWAN TALWKIES, BHAGWAN TAWLKIES-1, BHARTI FALI FARM, FARUKH ENGINEERING, GARG FURNITURE MARWARA ROAD ANAND NAGAR, GOGAJI TEMPLE SECTOR 13, GOPAL JI SUPER SPECIALITY HOSPITAL, GRAND CP, HOUSING POLICY, JAGHINA COLONY, JAGMOHANPURA, JANTA COLONY, KAUWA KA NAGLA, KRISHI UPAJ MANDI, KRISHI UPAJ MANDI SAMITI, KRISHNA BUILDING, KRISHNA HOTEL, KUMHER GATE SAMSHAN, MAHA LAXMI KRISHI YANTRALAYA, MAHADEV CONSTRUCTION, MASTI HOUSE, MOBILE TOWER IDHGAHA COLONY, MURWARA ROAD, NEAR GIRRAJ MEDICAL, NEAR IDEA TOWER, NEAR K MART SPM NAGAR, NEAR MICRO PC SOLUTION MARWARA ROAD ANAND NAGAR, NEAR SPM NAGAR GSS, NEETA GOYEL, NIRALA VIHAR COLONY, PINTU USHRANI JANTA COLONY, PNB BANK AD, RADHEY PIPE UDYOG, RAHAMANPURA, RAHAMANPURA - 1, RAHAMANPURA - 2, RAHAMANPURA-4, RAHMANPURA - 3, RAJ KIYA SCHOOL ANAND NAGAR, RAJASTHAN ASSOCIATION, RAMESHWER MUSHALE ANAND NAGAR, RAMESHWER MUSHALE ANAND NAGAR 1, RONAK MARRIAGE HALL, RONAK MARRIAGE HALL 1, S.R ATTA CHAKTI, SAI MANDIR ANAND NAGAR, SAI MANDIR ANAND NAGAR-1, SHAHNAI RESORT, SHYAM NAGAR RAHMANPURA, SWARAJ ARYA AGENCY, TAJ AGRO INDS.ANAND NAGAR, TATA MOTERS, VIDHYA FILLING STATION, WARD NO.1 KAMAL PURA VILLAGE', '28/02/2026 12:00 - 28/02/2026 13:00']

In [10]:
df

,Affected Area (at 28/02/2026 10:15),Duration (From - To)
0,"#1 - HEERADAS, SUBHAS NAGAR, ANAH GATE PARK, B...",28/02/2026 09:43 - 28/02/2026 10:59
1,"#2 - SPM NAGAR, ANAND NAGAR, AMARVIDHYA MANDIR...",28/02/2026 12:00 - 28/02/2026 13:00

In [11]:
df.to_csv(r'C:\Users\Anon\Desktop\MY PERSONAL SPACE\DATA SCIENCE LEARNINGS\power outage\test.csv')

In [12]:
df.iloc[:, 0]

0    #1 - HEERADAS, SUBHAS NAGAR, ANAH GATE PARK, B...
1    #2 - SPM NAGAR, ANAND NAGAR, AMARVIDHYA MANDIR...
Name: Affected Area (at 28/02/2026 10:15), dtype: str